# append cuda bin to path:
export CUDA_INSTALL_PATH=$HOME/geb/NVIDIA_CUDA_TOOLKIT_3.0
export CUDA_SDK_INSTALL_PATH=$HOME/geb/NVIDIA_CUDA_SDK_3.0/C
export CUDA_LIBS=$HOME/geb/NVIDIA_CUDA_TOOLKIT_3.0/lib:$HOME/geb/NVIDIA_CUDA_TOOLKIT_3.0/lib64
export MANPATH=:/man
export LD_LIBRARY_PATH=$CUDA_LIBS:$LD_LIBRARY_PATH
export PATH=$CUDA_INSTALL_PATH/bin:$PATH

